-- Corrige l'auto-génération de l'id sur chaque table indépendamment.
-- Chaque ALTER est isolé dans son propre bloc "exception" : si une table
-- a déjà l'auto-génération (comme "moments"), ça ne bloque plus les autres.

do $$
begin
  begin
    alter table moments alter column id add generated by default as identity;
  exception when others then
    raise notice 'moments.id déjà configuré (ok, on continue)';
  end;

  begin
    alter table bucket_items alter column id add generated by default as identity;
  exception when others then
    raise notice 'bucket_items.id déjà configuré (ok, on continue)';
  end;

  begin
    alter table prayer_topics alter column id add generated by default as identity;
  exception when others then
    raise notice 'prayer_topics.id déjà configuré (ok, on continue)';
  end;

  begin
    alter table game_sessions alter column id add generated by default as identity;
  exception when others then
    raise notice 'game_sessions.id déjà configuré (ok, on continue)';
  end;
end $$;

-- Resynchronise chaque compteur sur le plus grand id déjà présent,
-- pour éviter une collision au prochain insert.
do $$
begin
  begin
    perform setval(pg_get_serial_sequence('moments', 'id'), coalesce((select max(id) from moments), 1));
  exception when others then null;
  end;
  begin
    perform setval(pg_get_serial_sequence('bucket_items', 'id'), coalesce((select max(id) from bucket_items), 1));
  exception when others then null;
  end;
  begin
    perform setval(pg_get_serial_sequence('prayer_topics', 'id'), coalesce((select max(id) from prayer_topics), 1));
  exception when others then null;
  end;
  begin
    perform setval(pg_get_serial_sequence('game_sessions', 'id'), coalesce((select max(id) from game_sessions), 1));
  exception when others then null;
  end;
end $$;
