-- ═══════════════════════════════════════════════════════════════
-- Bulle — Script SQL maître, unique et rejouable sans risque.
-- Remplace tous les anciens scripts fragmentés (supabase_migration*.sql,
-- supabase_fix_id_*.sql, supabase_indexes_constraints.sql).
-- ═══════════════════════════════════════════════════════════════

create extension if not exists pgcrypto;

-- ─── 1. Auto-génération de l'id, quel que soit son type réel ──────
-- Détecte si chaque colonne "id" est numérique (bigint/int) ou texte
-- (text/uuid/varchar), et applique la bonne méthode de génération
-- automatique en conséquence. Ne casse rien si déjà correctement
-- configuré (chaque tentative est protégée individuellement).
do $$
declare
  t record;
  col_type text;
begin
  for t in
    select unnest(array['moments', 'bucket_items', 'prayer_topics', 'game_sessions']) as table_name
  loop
    select data_type into col_type
    from information_schema.columns
    where table_name = t.table_name and column_name = 'id';

    if col_type is null then
      raise notice 'Table % introuvable ou sans colonne id, ignorée', t.table_name;
      continue;
    end if;

    if col_type in ('bigint', 'integer', 'smallint') then
      begin
        execute format('alter table %I alter column id add generated by default as identity', t.table_name);
        raise notice '% : identity numérique appliquée', t.table_name;
      exception when others then
        raise notice '% : identity numérique déjà en place (ok)', t.table_name;
      end;
      begin
        execute format(
          'select setval(pg_get_serial_sequence(%L, ''id''), coalesce((select max(id) from %I), 1))',
          t.table_name, t.table_name
        );
      exception when others then null;
      end;
    else
      begin
        execute format('alter table %I alter column id set default gen_random_uuid()::text', t.table_name);
        raise notice '% : défaut UUID (texte) appliqué', t.table_name;
      exception when others then
        raise notice '% : défaut texte déjà en place (ok)', t.table_name;
      end;
    end if;
  end loop;
end $$;

-- ─── 2. Colonnes manquantes sur "moments" ──────────────────────────
alter table moments add column if not exists date timestamptz;
alter table moments add column if not exists location text;
alter table moments add column if not exists source text default 'manual';
alter table moments add column if not exists favorite boolean default false;
alter table moments add column if not exists updated_at timestamptz;
alter table moments add column if not exists deleted_at timestamptz;
alter table moments add column if not exists collection_ids text[] default '{}';
update moments set date = created_at where date is null;
update moments set updated_at = created_at where updated_at is null;

-- ─── 3. Colonne manquante sur "bucket_items" ───────────────────────
alter table bucket_items add column if not exists timing text not null default 'plus_tard';

-- ─── 4. Tables additionnelles (Collections, contenu personnalisé) ──
create table if not exists collections (
  id bigint generated by default as identity primary key,
  name text not null,
  cover_photo text,
  created_at timestamptz not null default now()
);

create table if not exists custom_questions (
  id bigint generated by default as identity primary key,
  theme text not null,
  question text not null,
  created_at timestamptz not null default now()
);

create table if not exists custom_defis (
  id bigint generated by default as identity primary key,
  text text not null,
  created_at timestamptz not null default now()
);

-- ─── 5. Index de performance ────────────────────────────────────────
create index if not exists idx_moments_created_at on moments (created_at desc);
create index if not exists idx_moments_date on moments (date desc);
create index if not exists idx_moments_source on moments (source);
create index if not exists idx_moments_deleted_at on moments (deleted_at);
create index if not exists idx_moments_favorite on moments (favorite) where favorite = true;
create index if not exists idx_bucket_items_completed on bucket_items (completed);
create index if not exists idx_bucket_items_timing on bucket_items (timing);
create index if not exists idx_prayer_topics_category on prayer_topics (category);
create index if not exists idx_prayer_topics_status on prayer_topics (status);
create index if not exists idx_game_sessions_played_at on game_sessions (played_at desc);
create index if not exists idx_custom_questions_theme on custom_questions (theme);

-- ─── 6. Garde-fous de cohérence des données ────────────────────────
do $$
begin
  begin
    alter table moments add constraint chk_moments_source
      check (source in ('manual', 'game', 'bucket', 'prayer'));
  exception when others then null;
  end;
  begin
    alter table bucket_items add constraint chk_bucket_items_timing
      check (timing in ('ce_soir', 'plus_tard'));
  exception when others then null;
  end;
  begin
    alter table prayer_topics add constraint chk_prayer_topics_category
      check (category in ('toport', 'recognition'));
  exception when others then null;
  end;
end $$;

-- ─── 7. Row Level Security ──────────────────────────────────────────
-- Désactivée pour un usage MVP avec la clé "anon" partagée entre les
-- deux utilisateurs du couple (pas d'authentification pour l'instant).
alter table moments disable row level security;
alter table bucket_items disable row level security;
alter table prayer_topics disable row level security;
alter table game_sessions disable row level security;
alter table collections disable row level security;
alter table custom_questions disable row level security;
alter table custom_defis disable row level security;

-- ─── 8. Stockage ────────────────────────────────────────────────────
-- Un bucket "photo_moment" (public) doit exister pour l'upload de photos.
-- Se crée manuellement dans Supabase → Storage → New bucket.
