-- ═══════════════════════════════════════════════════════════════
-- Bulle — Schéma Supabase complet (idempotent, peut être rejoué)
-- À exécuter dans Supabase → SQL Editor
-- ═══════════════════════════════════════════════════════════════

-- ─── Instants (table "moments") ────────────────────────────────
-- Table de base créée manuellement au départ (id, text, ambiance,
-- poetic, created_at, photo_url, source_id). On complète ici les
-- colonnes utilisées par l'app.
alter table moments add column if not exists date timestamptz;
alter table moments add column if not exists location text;
alter table moments add column if not exists source text default 'manual';
alter table moments add column if not exists favorite boolean default false;
alter table moments add column if not exists updated_at timestamptz;
alter table moments add column if not exists deleted_at timestamptz;
alter table moments add column if not exists collection_ids text[] default '{}';

update moments set date = created_at where date is null;
update moments set updated_at = created_at where updated_at is null;

-- Génération automatique de l'id (bigint identity), requis par l'app
-- qui n'envoie jamais d'id manuellement.
alter table moments alter column id add generated by default as identity;
alter table bucket_items alter column id add generated by default as identity;
alter table prayer_topics alter column id add generated by default as identity;
alter table game_sessions alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('moments', 'id'), coalesce((select max(id) from moments), 1));
select setval(pg_get_serial_sequence('bucket_items', 'id'), coalesce((select max(id) from bucket_items), 1));
select setval(pg_get_serial_sequence('prayer_topics', 'id'), coalesce((select max(id) from prayer_topics), 1));
select setval(pg_get_serial_sequence('game_sessions', 'id'), coalesce((select max(id) from game_sessions), 1));

-- ─── Envies (table "bucket_items") ─────────────────────────────
alter table bucket_items add column if not exists timing text not null default 'plus_tard';

-- ─── Collections ────────────────────────────────────────────────
create table if not exists collections (
  id bigint generated by default as identity primary key,
  name text not null,
  cover_photo text,
  created_at timestamptz not null default now()
);

-- ─── Contenu personnalisé : jeu "Qui connaît le mieux ?" et Défis ──
create table if not exists custom_questions (
  id bigint generated by default as identity primary key,
  theme text not null,
  question text not null,
  created_at timestamptz not null default now()
);

create table if not exists custom_defis (
  id bigint generated by default as identity primary key,
  text text not null,
  created_at timestamptz not null default now()
);

-- ─── Row Level Security ─────────────────────────────────────────
-- Désactivée pour un usage MVP avec la clé "anon" partagée entre les
-- deux utilisateurs du couple (pas d'authentification pour l'instant).
alter table moments disable row level security;
alter table bucket_items disable row level security;
alter table prayer_topics disable row level security;
alter table game_sessions disable row level security;
alter table collections disable row level security;
alter table custom_questions disable row level security;
alter table custom_defis disable row level security;

-- ─── Stockage ────────────────────────────────────────────────────
-- Un bucket "photos" (public) doit exister pour l'upload de photos
-- dans les instants. Se crée dans Supabase → Storage → New bucket.
